name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Print current working directory
      run: |
        pwd
        ls -la
    - name: Set up Python 3.13.1
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.1"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Docker Compose Setup
      uses: ndeloof/install-compose-action@v0.0.1

    - name: Start Docker Compose
      run: |
        docker-compose -f ./databases/docker-compose.yaml up -d
    - name: Wait for services to start
      run: |
        sleep 10  # Adjust sleep time depending on the container start time
    - name: Test with unittest
      run: |
        python -m unittest discover -s tests
    - name: Stop Docker Compose
      run: |
        docker-compose -f ./databases/docker-compose.yaml down
